name: just_test

on: [pull_request, push]

jobs:
  just_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install just || choco install just || sudo apt install just
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: python -m pip install pipenv || curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      # - run: python -m pipenv install
      - run: just test
